#!/bin/bash

DEBUG=
if test "x$1" = x-debug; then
	DEBUG=-debug
	shift
fi
FLAG=$1
test "x$FLAG" = x && FLAG=GB
FLAG=${FLAG%.png}.png

>lastcompiled.c
DIPLAY_PID=
while true; do
	sleep .05
	if diff -u lastcompiled.c waveflag.c; then
		continue
	fi

	if make &&
	   ./waveflag $DEBUG waved- $FLAG &&
	   cp waveflag.c lastcompiled.c ; then
		test -n "$DISPLAY_PID" && kill "$DISPLAY_PID"
		display waved-$FLAG &
		DISPLAY_PID=$!
	fi
done
