#!/bin/bash

>lastcompiled.c
DIPLAY_PID=
while true; do
	sleep .05
	if diff -u lastcompiled.c waveflag.c; then
		continue
	fi
	cp waveflag.c lastcompiled.c
	if gcc -std=c99 -Wall -Wextra lastcompiled.c `pkg-config --cflags --libs cairo` -o waveflag && ./waveflag waved- GB.png; then
		test -n "$DISPLAY_PID" && kill "$DISPLAY_PID"
		display waved-GB.png &
		DISPLAY_PID=$!
	fi
done
