#!/bin/bash

>lastcompiled.c
DIPLAY_PID=
while true; do
	sleep .05
	if diff -u lastcompiled.c waveflag.c; then
		continue
	fi
	cp waveflag.c lastcompiled.c
	if gcc lastcompiled.c `pkg-config --cflags --libs cairo` -o waveflag && ./waveflag; then
		test -n "$DISPLAY_PID" && kill "$DISPLAY_PID"
		display out.png &
		DISPLAY_PID=$!
	fi
done
